require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/libraries", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Library. As you add validations to Library, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Library.create! valid_attributes
      get libraries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      library = Library.create! valid_attributes
      get library_url(library)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_library_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      library = Library.create! valid_attributes
      get edit_library_url(library)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Library" do
        expect {
          post libraries_url, params: { library: valid_attributes }
        }.to change(Library, :count).by(1)
      end

      it "redirects to the created library" do
        post libraries_url, params: { library: valid_attributes }
        expect(response).to redirect_to(library_url(Library.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Library" do
        expect {
          post libraries_url, params: { library: invalid_attributes }
        }.to change(Library, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post libraries_url, params: { library: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested library" do
        library = Library.create! valid_attributes
        patch library_url(library), params: { library: new_attributes }
        library.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the library" do
        library = Library.create! valid_attributes
        patch library_url(library), params: { library: new_attributes }
        library.reload
        expect(response).to redirect_to(library_url(library))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        library = Library.create! valid_attributes
        patch library_url(library), params: { library: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested library" do
      library = Library.create! valid_attributes
      expect {
        delete library_url(library)
      }.to change(Library, :count).by(-1)
    end

    it "redirects to the libraries list" do
      library = Library.create! valid_attributes
      delete library_url(library)
      expect(response).to redirect_to(libraries_url)
    end
  end
end
